"""prioridade 5: contas_a_receber

Revision ID: 5433039d6678
Revises: 88a3462ceb76
Create Date: 2026-06-26 23:38:17.102703
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5433039d6678'
down_revision: Union[str, None] = '88a3462ceb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_a_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('id_pedido_canal', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contas_a_receber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_a_receber_canal'), ['canal'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_a_receber_id_pedido_canal'), ['id_pedido_canal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_a_receber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_a_receber_id_pedido_canal'))
        batch_op.drop_index(batch_op.f('ix_contas_a_receber_canal'))

    op.drop_table('contas_a_receber')
    # ### end Alembic commands ###
