"""initial schema: produtos, sku_map, sku_pendencias, vendas

Revision ID: 6b45a68cc6d3
Revises: 
Create Date: 2026-06-26 18:38:56.996845
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b45a68cc6d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_base', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1024), nullable=True),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_sku_base'), ['sku_base'], unique=True)

    op.create_table('sku_pendencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_canal', sa.String(length=50), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('id_anuncio', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('ocorrencias', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_canal', 'canal', name='uq_pendencia_sku_canal')
    )
    with op.batch_alter_table('sku_pendencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_pendencias_sku_canal'), ['sku_canal'], unique=False)

    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('id_pedido_canal', sa.String(length=50), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('status_canal', sa.String(length=255), nullable=False),
    sa.Column('status_erp', sa.String(length=20), nullable=False),
    sa.Column('sku_canal', sa.String(length=50), nullable=False),
    sa.Column('sku_base', sa.String(length=50), nullable=True),
    sa.Column('id_anuncio', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo_anuncio', sa.String(length=20), nullable=True),
    sa.Column('canal_logistico', sa.String(length=40), nullable=False),
    sa.Column('variacao', sa.String(length=255), nullable=True),
    sa.Column('qtd', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('receita_bruta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tarifas_plataforma', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frete_liquido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descontos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cancelamentos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquido_recebido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_pacote_multi', sa.Boolean(), nullable=False),
    sa.Column('importado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index('ix_venda_pedido_canal', ['canal', 'id_pedido_canal'], unique=False)

    op.create_table('sku_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_canal', sa.String(length=50), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('id_anuncio', sa.String(length=50), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('sku_base', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_canal', 'canal', name='uq_sku_canal_canal')
    )
    with op.batch_alter_table('sku_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_map_sku_canal'), ['sku_canal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sku_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_map_sku_canal'))

    op.drop_table('sku_map')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index('ix_venda_pedido_canal')

    op.drop_table('vendas')
    with op.batch_alter_table('sku_pendencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_pendencias_sku_canal'))

    op.drop_table('sku_pendencias')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_sku_base'))

    op.drop_table('produtos')
    # ### end Alembic commands ###
