"""prioridade 2: fornecedores, contatos, anexos e campos de produto

Revision ID: 767897683f84
Revises: 6b45a68cc6d3
Create Date: 2026-06-26 22:47:09.641806
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767897683f84'
down_revision: Union[str, None] = '6b45a68cc6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_tipo', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('caminho', sa.String(length=512), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.create_index('ix_anexo_owner', ['owner_tipo', 'owner_id'], unique=False)

    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('condicoes_pagamento_dias', sa.Integer(), nullable=True),
    sa.Column('prazo_medio_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_cnpj'), ['cnpj'], unique=True)

    op.create_table('contatos_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contatos_fornecedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contatos_fornecedor_fornecedor_id'), ['fornecedor_id'], unique=False)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('atributos', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('unidade_medida', sa.String(length=10), nullable=False, server_default='UN'))
        batch_op.add_column(sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('comprimento_cm', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('largura_cm', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('altura_cm', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ncm', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('aliquota_icms', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_pis', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_cofins', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_ipi', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('estoque_seguranca', sa.Numeric(precision=10, scale=3), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('preco_compra', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fornecedor_padrao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('produto_pai_id', sa.Integer(), nullable=True))
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2048),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_produtos_fornecedor_padrao_id'), ['fornecedor_padrao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_produto_pai_id'), ['produto_pai_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_produtos_fornecedor_padrao', 'fornecedores', ['fornecedor_padrao_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_produtos_produto_pai', 'produtos', ['produto_pai_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_produtos_produto_pai', type_='foreignkey')
        batch_op.drop_constraint('fk_produtos_fornecedor_padrao', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_produtos_produto_pai_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_fornecedor_padrao_id'))
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.drop_column('produto_pai_id')
        batch_op.drop_column('fornecedor_padrao_id')
        batch_op.drop_column('preco_compra')
        batch_op.drop_column('estoque_seguranca')
        batch_op.drop_column('estoque_minimo')
        batch_op.drop_column('aliquota_ipi')
        batch_op.drop_column('aliquota_cofins')
        batch_op.drop_column('aliquota_pis')
        batch_op.drop_column('aliquota_icms')
        batch_op.drop_column('ncm')
        batch_op.drop_column('altura_cm')
        batch_op.drop_column('largura_cm')
        batch_op.drop_column('comprimento_cm')
        batch_op.drop_column('peso_kg')
        batch_op.drop_column('unidade_medida')
        batch_op.drop_column('atributos')
        batch_op.drop_column('subcategoria')

    with op.batch_alter_table('contatos_fornecedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contatos_fornecedor_fornecedor_id'))

    op.drop_table('contatos_fornecedor')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_cnpj'))

    op.drop_table('fornecedores')
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_index('ix_anexo_owner')

    op.drop_table('anexos')
    # ### end Alembic commands ###
