"""prioridade 4: pedidos_compra, itens e contas_a_pagar

Revision ID: 88a3462ceb76
Revises: d11591e8d8c5
Create Date: 2026-06-26 23:20:53.062717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a3462ceb76'
down_revision: Union[str, None] = 'd11591e8d8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_compra_fornecedor_id'), ['fornecedor_id'], unique=False)

    op.create_table('contas_a_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('pedido_compra_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pedido_compra_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contas_a_pagar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_a_pagar_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_a_pagar_pedido_compra_id'), ['pedido_compra_id'], unique=False)

    op.create_table('itens_pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('qtd', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_compra_pedido_id'), ['pedido_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_compra_pedido_id'))

    op.drop_table('itens_pedido_compra')
    with op.batch_alter_table('contas_a_pagar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_a_pagar_pedido_compra_id'))
        batch_op.drop_index(batch_op.f('ix_contas_a_pagar_fornecedor_id'))

    op.drop_table('contas_a_pagar')
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_fornecedor_id'))

    op.drop_table('pedidos_compra')
    # ### end Alembic commands ###
