"""prioridade 3: locais, estoque_saldo e movimentos_estoque

Revision ID: d11591e8d8c5
Revises: 767897683f84
Create Date: 2026-06-26 23:08:55.967294
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11591e8d8c5'
down_revision: Union[str, None] = '767897683f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('estoque_saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('qtd_disponivel', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('qtd_reservada', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'local_id', name='uq_saldo_produto_local')
    )
    with op.batch_alter_table('estoque_saldo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoque_saldo_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_saldo_produto_id'), ['produto_id'], unique=False)

    op.create_table('movimentos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('qtd', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=True),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_produto_id'), ['produto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_local_id'))

    op.drop_table('movimentos_estoque')
    with op.batch_alter_table('estoque_saldo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_saldo_produto_id'))
        batch_op.drop_index(batch_op.f('ix_estoque_saldo_local_id'))

    op.drop_table('estoque_saldo')
    op.drop_table('locais')
    # ### end Alembic commands ###
